/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bulibrary.Nest;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author nattinun
 */
public class game extends javax.swing.JFrame {

  
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menubar = new javax.swing.JPanel();
        btnLogo = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnBookroom = new javax.swing.JLabel();
        btnBookGame = new javax.swing.JLabel();
        btnBooking = new javax.swing.JLabel();
        btnExite = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        bordgame = new javax.swing.JPanel();
        BtnHTP = new javax.swing.JLabel();
        BtnBordgame = new javax.swing.JLabel();
        BtnSalem = new javax.swing.JLabel();
        Salem = new javax.swing.JLabel();
        BtnBoss = new javax.swing.JLabel();
        Boss = new javax.swing.JLabel();
        BtnDuck = new javax.swing.JLabel();
        Duck = new javax.swing.JLabel();
        BtnSplendor = new javax.swing.JLabel();
        Splendor = new javax.swing.JLabel();
        BtnCat = new javax.swing.JLabel();
        Cat = new javax.swing.JLabel();
        BtnUNO = new javax.swing.JLabel();
        UNO = new javax.swing.JLabel();
        BtnWerewolf = new javax.swing.JLabel();
        Werewolf = new javax.swing.JLabel();
        BtnSpyfall = new javax.swing.JLabel();
        Spyfall = new javax.swing.JLabel();
        BGwhite = new javax.swing.JLabel();
        BGblue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menubar.setBackground(new java.awt.Color(255, 255, 255));
        Menubar.setOpaque(false);
        Menubar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BU library.png"))); // NOI18N
        btnLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoMouseClicked(evt);
            }
        });
        Menubar.add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"))); // NOI18N
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        Menubar.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 250, 280, 50));

        btnBookroom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"))); // NOI18N
        btnBookroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookroom.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBookroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookroomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookroomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookroomMouseExited(evt);
            }
        });
        Menubar.add(btnBookroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 350, 280, 60));

        btnBookGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"))); // NOI18N
        btnBookGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookGame.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBookGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookGameMouseExited(evt);
            }
        });
        Menubar.add(btnBookGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 450, 280, 50));

        btnBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"))); // NOI18N
        btnBooking.setToolTipText("");
        btnBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBooking.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        Menubar.add(btnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 550, 280, 50));

        btnExite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Exit.png"))); // NOI18N
        btnExite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExite.setPreferredSize(new java.awt.Dimension(166, 31));
        btnExite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExiteMouseExited(evt);
            }
        });
        Menubar.add(btnExite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 280, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Rectangle 4598.png"))); // NOI18N
        Menubar.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bordgame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/BtnHTPoff.png"))); // NOI18N
        BtnHTP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, -20, 1));
        BtnHTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bordgame.add(BtnHTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        BtnBordgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonBordgame.png"))); // NOI18N
        BtnBordgame.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, -20, 1));
        BtnBordgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bordgame.add(BtnBordgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        BtnSalem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnSalem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, -1, -1));

        Salem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/Salem.png"))); // NOI18N
        bordgame.add(Salem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        BtnBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, -1, -1));

        Boss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/TheBoss.png"))); // NOI18N
        bordgame.add(Boss, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        BtnDuck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnDuck, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, -1));

        Duck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/SittingDuckGallery.png"))); // NOI18N
        bordgame.add(Duck, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        BtnSplendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnSplendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, -1, -1));

        Splendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/Splendor.png"))); // NOI18N
        bordgame.add(Splendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, -1, -1));

        BtnCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, -1, -1));

        Cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ExplodingKittens.png"))); // NOI18N
        bordgame.add(Cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, -1, -1));

        BtnUNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        UNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/UNO.png"))); // NOI18N
        bordgame.add(UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        BtnWerewolf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnWerewolf, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        Werewolf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/Werewolf.png"))); // NOI18N
        bordgame.add(Werewolf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        BtnSpyfall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/ButtonSeleetBoardgame.png"))); // NOI18N
        bordgame.add(BtnSpyfall, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        Spyfall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/spyfall.png"))); // NOI18N
        bordgame.add(Spyfall, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        BGwhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/BGwhite.png"))); // NOI18N
        bordgame.add(BGwhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        BGblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/bordgame/BGblue.png"))); // NOI18N
        bordgame.add(BGblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        getContentPane().add(bordgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1270, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseClicked
        setMenu(false,false,false,false,true);

        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));

        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnLogoMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        btnUser.setIcon(icon);
        setMenu(true,false,false,false,false);

        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));

        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnUserMouseClicked

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        Icon ulicon = btnUser.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnUser.setIcon(en);
        }

    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        Icon ulicon = btnUser.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnUser.setIcon(normal);
        }
    }//GEN-LAST:event_btnUserMouseExited

    private void btnBookroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        btnBookroom.setIcon(icon);
        setMenu(false,false,true,false,false);

        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));

        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);

    }//GEN-LAST:event_btnBookroomMouseClicked

    private void btnBookroomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseEntered
        Icon ulicon = btnBookroom.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookroom.setIcon(en);
        }

    }//GEN-LAST:event_btnBookroomMouseEntered

    private void btnBookroomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseExited
        Icon ulicon = btnBookroom.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookroom.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookroomMouseExited

    private void btnBookGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        btnBookGame.setIcon(icon);
        setMenu(false,true,false,false,false);

        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));

        btnUser.setIcon(iconuser);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnBookGameMouseClicked

    private void btnBookGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseEntered
        Icon ulicon = btnBookGame.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookGame.setIcon(en);
        }
    }//GEN-LAST:event_btnBookGameMouseEntered

    private void btnBookGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseExited
        Icon ulicon = btnBookGame.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookGame.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookGameMouseExited

    private void btnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        btnBooking.setIcon(icon);
        setMenu(false,false,false,true,false);

        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));

        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnBookingMouseClicked

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        Icon ulicon = btnBooking.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBooking.setIcon(en);
        }
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        Icon ulicon = btnBooking.getIcon();
        String uliconURL = ulicon.toString();

        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEnnew.png"));

        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBooking.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnExiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExiteMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/ExitEnnew.png"));
        btnExite.setIcon(icon);
    }//GEN-LAST:event_btnExiteMouseEntered

    private void btnExiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExiteMouseExited

        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Exit.png"));
        btnExite.setIcon(icon);
    }//GEN-LAST:event_btnExiteMouseExited
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BGblue;
    private javax.swing.JLabel BGwhite;
    private javax.swing.JLabel Boss;
    private javax.swing.JLabel BtnBordgame;
    private javax.swing.JLabel BtnBoss;
    private javax.swing.JLabel BtnCat;
    private javax.swing.JLabel BtnDuck;
    private javax.swing.JLabel BtnHTP;
    private javax.swing.JLabel BtnSalem;
    private javax.swing.JLabel BtnSplendor;
    private javax.swing.JLabel BtnSpyfall;
    private javax.swing.JLabel BtnUNO;
    private javax.swing.JLabel BtnWerewolf;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Duck;
    private javax.swing.JPanel Menubar;
    private javax.swing.JLabel Salem;
    private javax.swing.JLabel Splendor;
    private javax.swing.JLabel Spyfall;
    private javax.swing.JLabel UNO;
    private javax.swing.JLabel Werewolf;
    private javax.swing.JPanel bordgame;
    private javax.swing.JLabel btnBookGame;
    private javax.swing.JLabel btnBooking;
    private javax.swing.JLabel btnBookroom;
    private javax.swing.JLabel btnExite;
    private javax.swing.JLabel btnLogo;
    private javax.swing.JLabel btnUser;
    // End of variables declaration//GEN-END:variables

    private void setMenu(boolean b, boolean b0, boolean b1, boolean b2, boolean b3) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
