/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bulibrary;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Windows 10
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        ButtonMenu = new javax.swing.JLabel();
        ButtonUser = new javax.swing.JLabel();
        BottonBookingRoom = new javax.swing.JLabel();
        BookingGame = new javax.swing.JLabel();
        BookingList = new javax.swing.JLabel();
        ButtonExit = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        Mainpage = new javax.swing.JPanel();
        StudyRoom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonOrderRoom = new javax.swing.JLabel();
        PicStudyRoom = new javax.swing.JLabel();
        PicBoardGame = new javax.swing.JLabel();
        BoardGame = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonOrderGame = new javax.swing.JLabel();
        BG2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setOpaque(false);
        jPanelMenu.setPreferredSize(new java.awt.Dimension(354, 864));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BU library.png"))); // NOI18N
        ButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMenu.add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        ButtonUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/User.png"))); // NOI18N
        ButtonUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonUserMouseExited(evt);
            }
        });
        jPanelMenu.add(ButtonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 250, 280, 50));

        BottonBookingRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BottonBookingRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/booking room.png"))); // NOI18N
        BottonBookingRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BottonBookingRoom.setPreferredSize(new java.awt.Dimension(166, 31));
        BottonBookingRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BottonBookingRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BottonBookingRoomMouseExited(evt);
            }
        });
        jPanelMenu.add(BottonBookingRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 350, 280, 60));

        BookingGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookingGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BookingGame.png"))); // NOI18N
        BookingGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingGame.setPreferredSize(new java.awt.Dimension(166, 31));
        BookingGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookingGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookingGameMouseExited(evt);
            }
        });
        jPanelMenu.add(BookingGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 450, 280, 50));

        BookingList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookingList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LIstBooking.png"))); // NOI18N
        BookingList.setToolTipText("");
        BookingList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingList.setPreferredSize(new java.awt.Dimension(166, 31));
        BookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookingListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookingListMouseExited(evt);
            }
        });
        jPanelMenu.add(BookingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 550, 280, 50));

        ButtonExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Exit.png"))); // NOI18N
        ButtonExit.setPreferredSize(new java.awt.Dimension(166, 31));
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonExitMouseExited(evt);
            }
        });
        jPanelMenu.add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 721, 280, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Rectangle 4598.png"))); // NOI18N
        BG.setText("jLabel1");
        jPanelMenu.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Mainpage.setBackground(new java.awt.Color(255, 255, 255));
        Mainpage.setOpaque(false);
        Mainpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudyRoom.setFont(new java.awt.Font("MN Mu Sate", 0, 48)); // NOI18N
        StudyRoom.setText("Study Room");
        StudyRoom.setToolTipText("");
        Mainpage.add(StudyRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/StudyRoomText.png"))); // NOI18N
        Mainpage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        ButtonOrderRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Proceed to order.png"))); // NOI18N
        ButtonOrderRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonOrderRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonOrderRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonOrderRoomMouseExited(evt);
            }
        });
        Mainpage.add(ButtonOrderRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        PicStudyRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/StudyRoom.png"))); // NOI18N
        Mainpage.add(PicStudyRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        PicBoardGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BoardGame.png"))); // NOI18N
        Mainpage.add(PicBoardGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        BoardGame.setFont(new java.awt.Font("MN Mu Sate", 0, 36)); // NOI18N
        BoardGame.setText("Board Game");
        Mainpage.add(BoardGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BoardGameText.png"))); // NOI18N
        Mainpage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, -1, -1));

        ButtonOrderGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Proceed to order.png"))); // NOI18N
        ButtonOrderGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonOrderGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonOrderGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonOrderGameMouseExited(evt);
            }
        });
        Mainpage.add(ButtonOrderGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 740, -1, -1));

        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Main Page.png"))); // NOI18N
        Mainpage.add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, -1, -1));

        getContentPane().add(Mainpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1270, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOrderRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOrderRoomMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/Proceed to orderEn.png")); 
        ButtonOrderRoom.setIcon(icon);
    }//GEN-LAST:event_ButtonOrderRoomMouseEntered

    private void ButtonOrderRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOrderRoomMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/Proceed to order.png")); 
        ButtonOrderRoom.setIcon(icon); 
    }//GEN-LAST:event_ButtonOrderRoomMouseExited

    private void ButtonOrderGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOrderGameMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/Proceed to orderEn.png")); 
        ButtonOrderGame.setIcon(icon);
    }//GEN-LAST:event_ButtonOrderGameMouseEntered

    private void ButtonOrderGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOrderGameMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/Proceed to order.png")); 
        ButtonOrderGame.setIcon(icon);
    }//GEN-LAST:event_ButtonOrderGameMouseExited

    private void ButtonUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUserMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/UserEn.png")); 
        ButtonUser.setIcon(icon); 
    }//GEN-LAST:event_ButtonUserMouseEntered

    private void ButtonUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUserMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/User.png")); 
        ButtonUser.setIcon(icon);
    }//GEN-LAST:event_ButtonUserMouseExited

    private void BottonBookingRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottonBookingRoomMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/booking roomEn.png")); 
        BottonBookingRoom.setIcon(icon);
    }//GEN-LAST:event_BottonBookingRoomMouseEntered

    private void BottonBookingRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BottonBookingRoomMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/booking room.png")); 
        BottonBookingRoom.setIcon(icon);
    }//GEN-LAST:event_BottonBookingRoomMouseExited

    private void BookingGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingGameMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/BookingGameEn.png")); 
        BookingGame.setIcon(icon);
    }//GEN-LAST:event_BookingGameMouseEntered

    private void BookingGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingGameMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/BookingGame.png")); 
        BookingGame.setIcon(icon);
    }//GEN-LAST:event_BookingGameMouseExited

    private void BookingListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingListMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/LIstBookingEn.png")); 
        BookingList.setIcon(icon);
    }//GEN-LAST:event_BookingListMouseEntered

    private void BookingListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingListMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/LIstBooking.png")); 
        BookingList.setIcon(icon);
    }//GEN-LAST:event_BookingListMouseExited

    private void ButtonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/ExitEn.png")); 
        ButtonExit.setIcon(icon);
    }//GEN-LAST:event_ButtonExitMouseEntered

    private void ButtonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseExited
        Icon icon = new ImageIcon(getClass().getResource("/Pictures/Exit.png")); 
        ButtonExit.setIcon(icon);
    }//GEN-LAST:event_ButtonExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BG2;
    private javax.swing.JLabel BoardGame;
    private javax.swing.JLabel BookingGame;
    private javax.swing.JLabel BookingList;
    private javax.swing.JLabel BottonBookingRoom;
    private javax.swing.JLabel ButtonExit;
    private javax.swing.JLabel ButtonMenu;
    private javax.swing.JLabel ButtonOrderGame;
    private javax.swing.JLabel ButtonOrderRoom;
    private javax.swing.JLabel ButtonUser;
    private javax.swing.JPanel Mainpage;
    private javax.swing.JLabel PicBoardGame;
    private javax.swing.JLabel PicStudyRoom;
    private javax.swing.JLabel StudyRoom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
