/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bulibrary;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mr.Phiphat
 */
public class JPStatus extends javax.swing.JPanel {

    /**
     * Creates new form JPStatus
     */
    public JPStatus() {
        initComponents();
    }
    public JPStatus(String stime,String etime,String Datastatus ){
        initComponents();
        ETime.setText(etime);
        STime.setText(stime);
        JSting1.setText(Datastatus);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSting = new javax.swing.JLabel();
        ETime = new javax.swing.JLabel();
        STime = new javax.swing.JLabel();
        JSting1 = new javax.swing.JLabel();
        IconBox2 = new javax.swing.JLabel();
        IconBox1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JSting.setFont(new java.awt.Font("Prompt Light", 0, 10)); // NOI18N
        JSting.setText("หมายเหตุ : ประชุมงาน");
        add(JSting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 30));

        ETime.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        ETime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ETime.setText("11:00");
        add(ETime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 50, 20));

        STime.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        STime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        STime.setText("09:00");
        add(STime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        JSting1.setFont(new java.awt.Font("Prompt Light", 0, 10)); // NOI18N
        add(JSting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 30));

        IconBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/boxTime.png"))); // NOI18N
        add(IconBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 40));

        IconBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/boxTime.png"))); // NOI18N
        add(IconBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 20, 10, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETime;
    private javax.swing.JLabel IconBox1;
    private javax.swing.JLabel IconBox2;
    private javax.swing.JLabel JSting;
    private javax.swing.JLabel JSting1;
    private javax.swing.JLabel STime;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
