/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bulibrary;

import bulibrary.ClassJava.DBConnect;
import bulibrary.ClassJava.UserData;
import bulibrary.ClassJava.ScrollBarCustom;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JScrollBar;
import net.miginfocom.swing.MigLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.chrono.ThaiBuddhistDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Mr.Phiphat
 */
public class StartMenu extends javax.swing.JPanel {
        private String firstName;
        private String lastName;
        private String email;
        private String studentId;
        private String phoneNumber;
        private String password;
        private static StartMenu instance = null;

        
    public StartMenu() {
        initComponents();
        setPreferredSize(new Dimension(1536, 864)); // กำหนดขนาดของ JPanel เพื่อให้ตรงกับ Test
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        scroll.setHorizontalScrollBar(sp);
        scroll.getViewport().setBackground(Color.WHITE);
        scrollMainmenu.setVerticalScrollBar(new ScrollBarCustom());
        scrollMainmenu.setHorizontalScrollBar(sp);
        scrollMainmenu.getViewport().setBackground(Color.WHITE);
        
        ScrollRoom.setVerticalScrollBar(new ScrollBarCustom());
        ScrollRoom.setHorizontalScrollBar(sp);
        ScrollRoom.getViewport().setBackground(Color.WHITE);
        
        ScrollBActvie.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBActvie.setHorizontalScrollBar(sp);
        ScrollBActvie.getViewport().setBackground(Color.WHITE);
        
        ScrollBComplet.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBComplet.setHorizontalScrollBar(sp);
        ScrollBComplet.getViewport().setBackground(Color.WHITE);
        
        setMenu(false, false, false, false, true);
        opacity1.setVisible(false);
        Pbooking.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));
        PbookingCompleted.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));
    }
    
    public static StartMenu getInstane(){
        if (instance == null) {
            instance = new StartMenu();
        }
        return instance;
    }
    
    public void setScroll(boolean isActive,boolean isCompleted){
        ScrollBActvie.setVisible(false);
    }
  
    public void setvisible(boolean isSet){
        setVisible(isSet);
    }
    public void setString(UserData user){
        firstName = user.getFirstName();
        lastName = user.getLastName();
        email = user.getEmail();
        studentId = user.getStudentId();
        phoneNumber = user.getPhoneNumber();
        password = user.getPassword();
        setTxtProfile();
    }
    public void setTxtProfile(){
        txtFname.setText(firstName);
        txtlname.setText(lastName);
        txtEmail.setText(email);
        txtID.setText(studentId);
        txtPhone.setText(phoneNumber);
        txtPass.setText(password);
   }
    public  void setMenu(boolean isUser,boolean isGmae,boolean isRoom,boolean isbooking,boolean ismain){
        User.setVisible(isUser);
        game.setVisible(isGmae);
        Room.setVisible(isRoom);
        Booking.setVisible(isbooking);
        mainmenu.setVisible(ismain);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menubar = new javax.swing.JPanel();
        btnLogo = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnBookroom = new javax.swing.JLabel();
        btnBookGame = new javax.swing.JLabel();
        btnBooking = new javax.swing.JLabel();
        btnExite = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        opacity1 = new javax.swing.JLabel();
        Booking = new javax.swing.JPanel();
        ScrollBActvie = new javax.swing.JScrollPane();
        Pbooking = new javax.swing.JPanel();
        ScrollBComplet = new javax.swing.JScrollPane();
        PbookingCompleted = new javax.swing.JPanel();
        active = new javax.swing.JLabel();
        completed = new javax.swing.JLabel();
        bgRoom1 = new javax.swing.JLabel();
        Room = new javax.swing.JPanel();
        ScrollRoom = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        btnC1 = new javax.swing.JLabel();
        btnR1 = new javax.swing.JLabel();
        btnC2 = new javax.swing.JLabel();
        btnR2 = new javax.swing.JLabel();
        btnR3 = new javax.swing.JLabel();
        btnC3 = new javax.swing.JLabel();
        btnR4 = new javax.swing.JLabel();
        btnC4 = new javax.swing.JLabel();
        btnR5 = new javax.swing.JLabel();
        btnC5 = new javax.swing.JLabel();
        btnR6 = new javax.swing.JLabel();
        btnC6 = new javax.swing.JLabel();
        btnR7 = new javax.swing.JLabel();
        btnC7 = new javax.swing.JLabel();
        btnR8 = new javax.swing.JLabel();
        btnC8 = new javax.swing.JLabel();
        btnC9 = new javax.swing.JLabel();
        btnR9 = new javax.swing.JLabel();
        btnC10 = new javax.swing.JLabel();
        btnR10 = new javax.swing.JLabel();
        BGbookroom = new javax.swing.JLabel();
        bgRoom = new javax.swing.JLabel();
        mainmenu = new javax.swing.JPanel();
        scrollMainmenu = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Bgmain = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        txtlname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();
        game = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menubar.setBackground(new java.awt.Color(255, 255, 255));
        Menubar.setOpaque(false);
        Menubar.setPreferredSize(new java.awt.Dimension(354, 864));
        Menubar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BU library.png"))); // NOI18N
        btnLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoMouseClicked(evt);
            }
        });
        Menubar.add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"))); // NOI18N
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        Menubar.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 250, 280, 50));

        btnBookroom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"))); // NOI18N
        btnBookroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookroom.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBookroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookroomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookroomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookroomMouseExited(evt);
            }
        });
        Menubar.add(btnBookroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 350, 280, 60));

        btnBookGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBookGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"))); // NOI18N
        btnBookGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookGame.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBookGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookGameMouseExited(evt);
            }
        });
        Menubar.add(btnBookGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 450, 280, 50));

        btnBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"))); // NOI18N
        btnBooking.setToolTipText("");
        btnBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBooking.setPreferredSize(new java.awt.Dimension(166, 31));
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        Menubar.add(btnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 550, 280, 50));

        btnExite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Exit.png"))); // NOI18N
        btnExite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExite.setPreferredSize(new java.awt.Dimension(166, 31));
        btnExite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExiteMouseExited(evt);
            }
        });
        Menubar.add(btnExite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 280, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Rectangle 4598.png"))); // NOI18N
        Menubar.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        opacity1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/opacity.png"))); // NOI18N
        opacity1.setText("jLabel4");
        add(opacity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -18, 1540, 900));

        Booking.setBackground(new java.awt.Color(236, 248, 255));
        Booking.setPreferredSize(new java.awt.Dimension(1260, 880));
        Booking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollBActvie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollBActvie.setAutoscrolls(true);
        ScrollBActvie.setOpaque(false);

        Pbooking.setBackground(new java.awt.Color(255, 255, 255));
        Pbooking.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PbookingLayout = new javax.swing.GroupLayout(Pbooking);
        Pbooking.setLayout(PbookingLayout);
        PbookingLayout.setHorizontalGroup(
            PbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        PbookingLayout.setVerticalGroup(
            PbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        ScrollBActvie.setViewportView(Pbooking);

        Booking.add(ScrollBActvie, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1170, 780));

        ScrollBComplet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollBComplet.setAutoscrolls(true);
        ScrollBComplet.setOpaque(false);

        PbookingCompleted.setBackground(new java.awt.Color(255, 255, 255));
        PbookingCompleted.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PbookingCompletedLayout = new javax.swing.GroupLayout(PbookingCompleted);
        PbookingCompleted.setLayout(PbookingCompletedLayout);
        PbookingCompletedLayout.setHorizontalGroup(
            PbookingCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        PbookingCompletedLayout.setVerticalGroup(
            PbookingCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        ScrollBComplet.setViewportView(PbookingCompleted);

        Booking.add(ScrollBComplet, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1170, 780));

        active.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/booking/Active.png"))); // NOI18N
        active.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        active.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeMouseClicked(evt);
            }
        });
        Booking.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 58, -1, -1));

        completed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/booking/Completed.png"))); // NOI18N
        completed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        completed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completedMouseClicked(evt);
            }
        });
        Booking.add(completed, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 58, -1, -1));

        bgRoom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/bg.png"))); // NOI18N
        Booking.add(bgRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        add(Booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1280, -1));

        Room.setBackground(new java.awt.Color(236, 248, 255));
        Room.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollRoom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollRoom.setForeground(new java.awt.Color(255, 255, 255));
        ScrollRoom.setAutoscrolls(true);
        ScrollRoom.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC1MouseClicked(evt);
            }
        });
        jPanel3.add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 100, 30));

        btnR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR1MouseClicked(evt);
            }
        });
        jPanel3.add(btnR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 100, 30));

        btnC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC2MouseClicked(evt);
            }
        });
        jPanel3.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 40, -1, 30));

        btnR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR2MouseClicked(evt);
            }
        });
        jPanel3.add(btnR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 100, -1, 30));

        btnR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR3MouseClicked(evt);
            }
        });
        btnR3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnR3KeyPressed(evt);
            }
        });
        jPanel3.add(btnR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 298, -1, -1));

        btnC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC3MouseClicked(evt);
            }
        });
        jPanel3.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 238, 100, 30));

        btnR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR4MouseClicked(evt);
            }
        });
        jPanel3.add(btnR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 298, -1, -1));

        btnC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC4MouseClicked(evt);
            }
        });
        jPanel3.add(btnC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 238, 100, 30));

        btnR5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR5MouseClicked(evt);
            }
        });
        jPanel3.add(btnR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        btnC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC5MouseClicked(evt);
            }
        });
        jPanel3.add(btnC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 100, 30));

        btnR6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR6MouseClicked(evt);
            }
        });
        jPanel3.add(btnR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 100, -1));

        btnC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC6MouseClicked(evt);
            }
        });
        jPanel3.add(btnC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 100, 30));

        btnR7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR7MouseClicked(evt);
            }
        });
        jPanel3.add(btnR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 100, 40));

        btnC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC7MouseClicked(evt);
            }
        });
        jPanel3.add(btnC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 100, 40));

        btnR8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR8MouseClicked(evt);
            }
        });
        jPanel3.add(btnR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 680, -1, 40));

        btnC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC8MouseClicked(evt);
            }
        });
        jPanel3.add(btnC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 620, -1, 40));

        btnC9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC9MouseClicked(evt);
            }
        });
        jPanel3.add(btnC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 820, 100, 30));

        btnR9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR9MouseClicked(evt);
            }
        });
        jPanel3.add(btnR9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 880, 100, 30));

        btnC10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btncheck.png"))); // NOI18N
        btnC10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnC10MouseClicked(evt);
            }
        });
        jPanel3.add(btnC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 820, 100, 30));

        btnR10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/btnBookingroom.png"))); // NOI18N
        btnR10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnR10MouseClicked(evt);
            }
        });
        jPanel3.add(btnR10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 880, 100, 30));

        BGbookroom.setBackground(new java.awt.Color(255, 255, 255));
        BGbookroom.setForeground(new java.awt.Color(255, 255, 255));
        BGbookroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/data.png"))); // NOI18N
        BGbookroom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, -10));
        jPanel3.add(BGbookroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 948));

        ScrollRoom.setViewportView(jPanel3);

        Room.add(ScrollRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1170, 780));

        bgRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Room/bg.png"))); // NOI18N
        Room.add(bgRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        add(Room, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1280, -1));

        mainmenu.setBackground(new java.awt.Color(255, 255, 255));

        scrollMainmenu.setBackground(new java.awt.Color(255, 255, 255));
        scrollMainmenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollMainmenu.setForeground(new java.awt.Color(255, 255, 255));
        scrollMainmenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollMainmenu.setToolTipText("");
        scrollMainmenu.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollMainmenu.setAlignmentX(10.0F);
        scrollMainmenu.setAlignmentY(10.0F);
        scrollMainmenu.setAutoscrolls(true);
        scrollMainmenu.setColumnHeaderView(null);
        scrollMainmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollMainmenu.setNextFocusableComponent(jPanel4);
        scrollMainmenu.setOpaque(false);
        scrollMainmenu.setViewportView(btnUpdate);

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/btnRoommain.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/btnGamemain.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        Bgmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/หน้าหลัก.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(741, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(125, 125, 125))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bgmain)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(947, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bgmain)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);

        scrollMainmenu.setViewportView(jPanel1);

        javax.swing.GroupLayout mainmenuLayout = new javax.swing.GroupLayout(mainmenu);
        mainmenu.setLayout(mainmenuLayout);
        mainmenuLayout.setHorizontalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainmenuLayout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(scrollMainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        mainmenuLayout.setVerticalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainmenuLayout.createSequentialGroup()
                    .addComponent(scrollMainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1280, 870));

        User.setBackground(new java.awt.Color(255, 255, 255));

        txtlname.setText("First name");
        txtlname.setBorder(null);

        txtEmail.setText("First name");
        txtEmail.setBorder(null);

        txtFname.setText("First name");
        txtFname.setBorder(null);

        txtID.setText("First name");
        txtID.setBorder(null);

        txtPass.setText("First name");
        txtPass.setBorder(null);

        txtPhone.setText("First name");
        txtPhone.setBorder(null);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/btnProfile.png"))); // NOI18N
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Profile edite.png"))); // NOI18N

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)))
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnUpdate))
        );

        add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1280, 870));

        game.setBackground(new java.awt.Color(236, 248, 255));
        game.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scroll.setForeground(new java.awt.Color(255, 255, 255));
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setToolTipText("");
        scroll.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scroll.setAlignmentX(10.0F);
        scroll.setAlignmentY(10.0F);
        scroll.setAutoscrolls(true);
        scroll.setColumnHeaderView(null);
        scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scroll.setNextFocusableComponent(jPanel4);
        scroll.setOpaque(false);
        scroll.setViewportView(btnUpdate);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kuy");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1220, 90, 60));

        jLabel3.setText("Kuy");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 60));

        scroll.setViewportView(jPanel4);

        game.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1170, 750));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Bgscroll.png"))); // NOI18N
        game.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1230, 810));

        add(game, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -8, 1280, 890));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        Icon ulicon = btnUser.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnUser.setIcon(en);
        }

    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        Icon ulicon = btnUser.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnUser.setIcon(normal);
        }
    }//GEN-LAST:event_btnUserMouseExited

    private void btnBookroomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseEntered
        Icon ulicon = btnBookroom.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookroom.setIcon(en);
        }
        
    }//GEN-LAST:event_btnBookroomMouseEntered

    private void btnBookroomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseExited
        Icon ulicon = btnBookroom.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookroom.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookroomMouseExited

    private void btnBookGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseEntered
        Icon ulicon = btnBookGame.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookGame.setIcon(en);
        }
    }//GEN-LAST:event_btnBookGameMouseEntered

    private void btnBookGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseExited
        Icon ulicon = btnBookGame.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBookGame.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookGameMouseExited

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        Icon ulicon = btnBooking.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBooking.setIcon(en);
        }
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        Icon ulicon = btnBooking.getIcon();
        String uliconURL = ulicon.toString();
        
        Icon normal = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon click = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        Icon en = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEnnew.png"));
        
        if (uliconURL.equals(click.toString())) {
            System.out.println("Ok");
        } else {
            btnBooking.setIcon(normal);
        }
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnExiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExiteMouseEntered
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/ExitEnnew.png"));
        btnExite.setIcon(icon);
    }//GEN-LAST:event_btnExiteMouseEntered

    private void btnExiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExiteMouseExited
        
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/Exit.png"));
        btnExite.setIcon(icon);
    }//GEN-LAST:event_btnExiteMouseExited

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/UserEn.png"));
        btnUser.setIcon(icon);
        setMenu(true,false,false,false,false);
        
        
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        
        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);

    }//GEN-LAST:event_btnUserMouseClicked

    private void btnBookroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookroomMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking roomEn.png"));
        btnBookroom.setIcon(icon);
        setMenu(false,false,true,false,false);
        
        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        
        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);
        
    }//GEN-LAST:event_btnBookroomMouseClicked
//
    private void btnBookGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookGameMouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGameEn.png"));
        btnBookGame.setIcon(icon);
        setMenu(false,true,false,false,false);
        
        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
       
        btnUser.setIcon(iconuser);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnBookGameMouseClicked

    private void btnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseClicked
        Pbooking.removeAll(); 
        SetScroll(true, false);
        Icon active = new ImageIcon(getClass().getResource("/bulibrary/image/booking/ActiveEx.png"));
        this.active.setIcon(active);
        
        Icon compIcon = new ImageIcon(getClass().getResource("/bulibrary/image/booking/Completed.png"));
        this.completed.setIcon(compIcon);
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBookingEn.png"));
        btnBooking.setIcon(icon);
        setMenu(false,false,false,true,false);
        
        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBookroom.setIcon(iconroom);
        
        String emailToSearch = email; // อีเมลที่ต้องการค้นหา
        String selectQuery = "SELECT * FROM booking WHERE email = ?";
        DBConnect conn = new DBConnect();
        ResultSet rs = null;

        try {
            PreparedStatement statement = conn.prepareStatement(selectQuery);
            statement.setString(1, emailToSearch);

            rs = statement.executeQuery();
            while (rs.next()) {
                String room = rs.getString("room");
                String date = rs.getString("date");
                String startTime = rs.getString("stime");
                String endTime = rs.getString("etime");

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                DateTimeFormatter ThaiFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                try {
                    // แปลงวันที่จาก DB เป็น LocalDate
                    LocalDate dateFromDB = LocalDate.parse(date, formatter);
                    ThaiBuddhistDate thaiBuddhistDate = ThaiBuddhistDate.now();
                    String lastDate = thaiBuddhistDate.toString().substring(thaiBuddhistDate.toString().length() - 10);
                    
                    
                    if (dateFromDB.isAfter(LocalDate.parse(lastDate, ThaiFormatter)) || dateFromDB.isEqual(LocalDate.parse(lastDate, ThaiFormatter))) {
                        System.out.println(dateFromDB);
                        System.out.println(lastDate);

                        // กระทำเมื่อ dateFromDB อยู่ในอนาคต
                        String user = firstName + lastName;
                        Component panel = Pbooking;
                        Component add = Pbooking.add(new JPbooking(user, studentId, startTime, endTime, room, date, panel));
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            rs.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }



    }//GEN-LAST:event_btnBookingMouseClicked

    private void btnLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseClicked
        setMenu(false,false,false,false,true);
        
        Icon iconuser = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/User.png"));
        Icon icongame = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/BookingGame.png"));
        Icon iconbook = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/LIstBooking.png"));
        Icon iconroom = new ImageIcon(getClass().getResource("/bulibrary/image/Iconmenubar/booking room.png"));
        
        btnUser.setIcon(iconuser);
        btnBookGame.setIcon(icongame);
        btnBooking.setIcon(iconbook);
        btnBookroom.setIcon(iconroom);
    }//GEN-LAST:event_btnLogoMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setMenu(false,false,true,false,false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        setMenu(false,true,false,false,false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

        if (txtFname.getText().isEmpty()) {
            String text = "Please enter first name.";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
        } else if (txtlname.getText().isEmpty()) {
            String text = "Please enter last name. .";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
        } else if (txtEmail.getText().isEmpty()){
            String text = "Please enter email address.";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
  
        } else if (txtID.getText().isEmpty())  {
            String text = "Please enter student ID.";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
        } else if (txtPhone.getText().isEmpty()) {
            String text = "Please enter telephone number.";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
        } else if (txtPass.getText().isEmpty()) {
            String text = "Please enter your password.";
            String url = "/bulibrary/image/crossAnimat.png";
            WarningMessage warnmessage = new WarningMessage(new javax.swing.JFrame(),true,url,text);
            warnmessage.setVisible(true);
        } else {
                opacity1.setVisible(true);
                UserData user = new UserData();
                user.setFirstName(txtFname.getText());
                user.setLastName(txtlname.getText());
                user.setEmail(txtEmail.getText());
                user.setPhoneNumber(txtPhone.getText());
                user.setStudentId(txtID.getText());
                user.setPassword(txtPass.getText());
                
                setString(user);
                 String warning = "Are you confirm ChangeProfile";
                DialogUpdate dialog = new DialogUpdate(new javax.swing.JFrame(), true, user,warning,email);
                dialog.setVisible(true);
                opacity1.setVisible(false);
                
        }
   
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnExiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExiteMouseClicked
        StartApp.getInstance().changePanelVisibility(true, false, false);
    }//GEN-LAST:event_btnExiteMouseClicked

    private void btnC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC1MouseClicked
        opacity1.setVisible(true);
        String room = "Room1";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC1MouseClicked

    private void btnC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MouseClicked
         opacity1.setVisible(true);
        String room = "Room2";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC2MouseClicked

    private void btnC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC3MouseClicked
         opacity1.setVisible(true);
        String room = "Room3";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC3MouseClicked

    private void btnC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC4MouseClicked
         opacity1.setVisible(true);
        String room = "Room4";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC4MouseClicked

    private void btnC5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC5MouseClicked
         opacity1.setVisible(true);
        String room = "Room5";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC5MouseClicked

    private void btnC6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC6MouseClicked
         opacity1.setVisible(true);
        String room = "Room6";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC6MouseClicked

    private void btnC7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC7MouseClicked
         opacity1.setVisible(true);
        String room = "Room7";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC7MouseClicked

    private void btnC8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC8MouseClicked
         opacity1.setVisible(true);
        String room = "Room8";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC8MouseClicked

    private void btnC9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC9MouseClicked
         opacity1.setVisible(true);
        String room = "Room9";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC9MouseClicked

    private void btnC10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC10MouseClicked
        opacity1.setVisible(true);
        String room = "Room10";
        RoomStatus Droom = new RoomStatus(new javax.swing.JFrame(), true, room);
        Droom.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnC10MouseClicked

    private void btnR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR1MouseClicked
        opacity1.setVisible(true);
        String room = "Room1";
       
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR1MouseClicked

    private void btnR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR2MouseClicked
        opacity1.setVisible(true);
        String room = "Room2";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR2MouseClicked

    private void btnR3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnR3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnR3KeyPressed

    private void btnR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR3MouseClicked
        opacity1.setVisible(true);
        String room = "Room3";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR3MouseClicked

    private void btnR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR4MouseClicked
        opacity1.setVisible(true);
        String room = "Room4";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR4MouseClicked

    private void btnR5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR5MouseClicked
        opacity1.setVisible(true);
        String room = "Room5";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR5MouseClicked

    private void btnR6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR6MouseClicked
        opacity1.setVisible(true);
        String room = "Room6";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR6MouseClicked

    private void btnR7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR7MouseClicked
        opacity1.setVisible(true);
        String room = "Room7";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR7MouseClicked

    private void btnR8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR8MouseClicked
        opacity1.setVisible(true);
        String room = "Room8";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR8MouseClicked

    private void btnR9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR9MouseClicked
        opacity1.setVisible(true);
        String room = "Room9";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR9MouseClicked

    private void btnR10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnR10MouseClicked
        opacity1.setVisible(true);
        String room = "Room10";
        String email = UserData.getInstane().getEmail();
        String id = UserData.getInstane().getStudentId();
        String user = UserData.getInstane().getUser();
        BookingRoom book = new BookingRoom(new javax.swing.JFrame(), true,room,user,id,email);
        book.setVisible(true);
        opacity1.setVisible(false);
    }//GEN-LAST:event_btnR10MouseClicked
    public void SetScroll(boolean isActive, boolean isComplet){
        ScrollBActvie.setVisible(isActive);
        ScrollBComplet.setVisible(isComplet);
    }
    private void completedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completedMouseClicked
        SetScroll(false, true);
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/booking/CompletedEx.png"));
        completed.setIcon(icon);
        PbookingCompleted.removeAll();
        Icon iconac = new ImageIcon(getClass().getResource("/bulibrary/image/booking/active.png"));
        active.setIcon(iconac);
        
        
        String emailToSearch = email; // อีเมลที่ต้องการค้นหา
        String selectQuery = "SELECT * FROM booking WHERE email = ?";
        DBConnect conn = new DBConnect();
        ResultSet rs = null;

        try {
            PreparedStatement statement = conn.prepareStatement(selectQuery);
            statement.setString(1, emailToSearch);

            rs = statement.executeQuery();
            while (rs.next()) {
                String room = rs.getString("room");
                String date = rs.getString("date");
                String startTime = rs.getString("stime");
                String endTime = rs.getString("etime");

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                DateTimeFormatter ThaiFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                try {
                    // แปลงวันที่จาก DB เป็น LocalDate
                    LocalDate dateFromDB = LocalDate.parse(date, formatter);
                    ThaiBuddhistDate thaiBuddhistDate = ThaiBuddhistDate.now();
                    String lastDate = thaiBuddhistDate.toString().substring(thaiBuddhistDate.toString().length() - 10);
                    
                    
                    if (dateFromDB.isBefore(LocalDate.parse(lastDate, ThaiFormatter))) {
                        System.out.println(dateFromDB);
                        System.out.println(lastDate);

                        // กระทำเมื่อ dateFromDB อยู่ในอดีต
                        String user = firstName + lastName;
                        Component panel = Pbooking;
                        Component add = PbookingCompleted.add(new JPbookComplet(user, studentId, startTime, endTime, room, date, panel));
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            rs.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_completedMouseClicked

    private void activeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeMouseClicked
        SetScroll(true, false);
        Icon icon = new ImageIcon(getClass().getResource("/bulibrary/image/booking/ActiveEx.png"));
        active.setIcon(icon);
        
        Icon iconcom = new ImageIcon(getClass().getResource("/bulibrary/image/booking/Completed.png"));
        completed.setIcon(iconcom);
        
        Pbooking.removeAll(); 
        
        String emailToSearch = email; // อีเมลที่ต้องการค้นหา
        String selectQuery = "SELECT * FROM booking WHERE email = ?";
        DBConnect conn = new DBConnect();
        ResultSet rs = null;

        try {
            PreparedStatement statement = conn.prepareStatement(selectQuery);
            statement.setString(1, emailToSearch);

            rs = statement.executeQuery();
            while (rs.next()) {
                String room = rs.getString("room");
                String date = rs.getString("date");
                String startTime = rs.getString("stime");
                String endTime = rs.getString("etime");

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                DateTimeFormatter ThaiFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                try {
                    // แปลงวันที่จาก DB เป็น LocalDate
                    LocalDate dateFromDB = LocalDate.parse(date, formatter);
                    ThaiBuddhistDate thaiBuddhistDate = ThaiBuddhistDate.now();
                    String lastDate = thaiBuddhistDate.toString().substring(thaiBuddhistDate.toString().length() - 10);
                    
                    
                    if (dateFromDB.isAfter(LocalDate.parse(lastDate, ThaiFormatter)) || dateFromDB.isEqual(LocalDate.parse(lastDate, ThaiFormatter))) {
                        System.out.println(dateFromDB);
                        System.out.println(lastDate);

                        // กระทำเมื่อ dateFromDB อยู่ในอนาคต
                        String user = firstName + lastName;
                        Component panel = Pbooking;
                        Component add = Pbooking.add(new JPbooking(user, studentId, startTime, endTime, room, date, panel));
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
            rs.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_activeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BGbookroom;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Bgmain;
    private javax.swing.JPanel Booking;
    private javax.swing.JPanel Menubar;
    private javax.swing.JPanel Pbooking;
    private javax.swing.JPanel PbookingCompleted;
    private javax.swing.JPanel Room;
    private javax.swing.JScrollPane ScrollBActvie;
    private javax.swing.JScrollPane ScrollBComplet;
    private javax.swing.JScrollPane ScrollRoom;
    private javax.swing.JPanel User;
    private javax.swing.JLabel active;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgRoom;
    private javax.swing.JLabel bgRoom1;
    private javax.swing.JLabel btnBookGame;
    private javax.swing.JLabel btnBooking;
    private javax.swing.JLabel btnBookroom;
    private javax.swing.JLabel btnC1;
    private javax.swing.JLabel btnC10;
    private javax.swing.JLabel btnC2;
    private javax.swing.JLabel btnC3;
    private javax.swing.JLabel btnC4;
    private javax.swing.JLabel btnC5;
    private javax.swing.JLabel btnC6;
    private javax.swing.JLabel btnC7;
    private javax.swing.JLabel btnC8;
    private javax.swing.JLabel btnC9;
    private javax.swing.JLabel btnExite;
    private javax.swing.JLabel btnLogo;
    private javax.swing.JLabel btnR1;
    private javax.swing.JLabel btnR10;
    private javax.swing.JLabel btnR2;
    private javax.swing.JLabel btnR3;
    private javax.swing.JLabel btnR4;
    private javax.swing.JLabel btnR5;
    private javax.swing.JLabel btnR6;
    private javax.swing.JLabel btnR7;
    private javax.swing.JLabel btnR8;
    private javax.swing.JLabel btnR9;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel completed;
    private javax.swing.JPanel game;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainmenu;
    private javax.swing.JLabel opacity1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scrollMainmenu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
