/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bulibrary;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mr.Phiphat
 */
public class WarningMessage extends javax.swing.JDialog {

    /**
     * Creates new form WarningMessage
     */
    public WarningMessage(java.awt.Frame parent, boolean modal,String url,String text) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        Icon icon = new ImageIcon(getClass().getResource(url));
        animation.setIcon(icon);
        tWarning.setText("<html><div style='text-align: center;'>" + text + "</div></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tWarning = new javax.swing.JLabel();
        animation = new javax.swing.JLabel();
        Exite = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tWarning.setFont(new java.awt.Font("Airbnb Cereal App Medium", 1, 20)); // NOI18N
        tWarning.setForeground(new java.awt.Color(102, 102, 102));
        tWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tWarning.setToolTipText("");
        getContentPane().add(tWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 180, 469, 50));

        animation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(animation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, 130));

        Exite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/CrossExit.png"))); // NOI18N
        Exite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExiteMouseClicked(evt);
            }
        });
        getContentPane().add(Exite, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulibrary/image/warningBG.png"))); // NOI18N
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExiteMouseClicked
        dispose();
    }//GEN-LAST:event_ExiteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarningMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarningMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarningMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarningMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String text = "Please fill in complete information:";
                String url = "/bulibrary/image/crossAnimat.png";
                WarningMessage dialog = new WarningMessage(new javax.swing.JFrame(), true,url,text);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Exite;
    private javax.swing.JLabel animation;
    private javax.swing.JLabel tWarning;
    // End of variables declaration//GEN-END:variables
}
